### ISSUE TITLE
Klasterizacija cvetova

### ISSUE THREAD

**Issue by msuvajdzic24** [ftn-ai-lab/ori-2017-e2#12]
Ko su članovi tima, grupa sa vežbi? Ime, prezime, broj indeksa...
Milan Suvajdžić, RA139/2014 Grupa 5

Problem koji se rešava (detaljniji opis):
Klasterovanje slika cvetova u 5 grupa:
1. visibabe
2. ljubicice
3. suncokreti
4. bela rada
5. maslacak

Algoritam/algoritmi koji će se koristiti:
Koristiću K-MEANS algoritam.

Metrika za poređenje performansi:
Procenat slika koje su tacno klasterizovane.

Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?
Podaci su sakupljeni sa sajta http://www.robots.ox.ac.uk/~vgg/data/flowers/17/index.html.

Na koji način planirate validaciju rešenja?
Validacija resenja ce se izvrsiti odabirom fiksnog broja slika iz svake grupe cvetova. Na kraju ću izraziti tačnost klasterizacije nad odabranim slikama u procentima.

Asistent Dragan Vidakovic

**Comment by vdragan1993** [comment]
Problem je isuviše jednostavan za projekat, morate ga ili promeniti ili proširiti.

**Comment by msuvajdzic24** [comment]
Postovani,
Posto danas nisam stigao da upisem ocenu,  da li mozete da kazete profesoru
da posalje ocenu na sluzbu,  da mi ne propadne, ili da mi date mejl od
profesora posto nmg da ga nadjem.
Unapred zahvalan,
Milan Suvajdzic RA139-2014
