### ISSUE TITLE
Klasterizacija leptira

### ISSUE THREAD

**Issue by Aco95** [ftn-ai-lab/ori-2017-e2#13]
Ko su članovi tima, grupa sa vežbi? Ime, prezime, broj indeksa...
Arsenije Degenek, RA59-2014 Grupa 5

Problem koji se rešava (detaljniji opis):
Klasterizovanje slika leptira u 10 grupa:
     1. Monarch butterfly
     2. Zebra longwing
     3. Red postman
     4. Buckeye
     5. Small copper
     6. Mourning cloak
     7. Giant swallowtail
     8. White butterfly
     9. Red admiral
    10. Painted lady

Algoritam/algoritmi koji će se koristiti:
K-MEANS algoritam

Metrika za poređenje performansi algoritama i/ili parametara algoritma:
Procenat slika koje su tacno klasterizovane.

Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?
Dataset preuzet sa sajta: http://www.comp.leeds.ac.uk/scs6jwks/dataset/leedsbutterfly/

Na koji način planirate validaciju rešenja?
Odabirom fiksnog broja slika iz svake grupe leptira. Na kraju se procentualno izrazava tacnost klasterizacije nad odabranim slikama

Asistent Dragan Vidakovic

**Comment by vdragan1993** [comment]
Problem je isuviše jednostavan za projekat, morate ga ili promeniti ili proširiti.
