### ISSUE TITLE
klasterizacija ptičijih vrsta

### ISSUE THREAD

**Issue by jovica27** [ftn-ai-lab/ori-2017-e2#16]
**Ko su članovi tima, grupa sa vezbi, Ime prezime, broj indeksa..**
Jovica  Čubrić, ra142-2014 Grupa 2

**Problem koji se rešava:**
Potrebno je  da se na osnovu karakteristika prosledjene slike, ptica pridruzi odgovarajućoj grupi. Zbog brzeg rada koristiće se manji broj vrsta ptica  (4 vrste).
- Ptica rugalica
- Čadjavi albatros
- Braon pelikan
- Beli pelikan

**Algoritam koji se koristi:**
Koristiće se k-means algoritam.

**Metrika za poredjenje performansi:**
Procenat slika koje su tačno dodeljene grupi kojoj pripadaju.

**Podaci koji se koriste - da li su već dodstupni online, da li će se skupljati automatski ili manuelno?**
Za projekat će se koristiti data set sa sajta  http://www.vision.caltech.edu/visipedia/CUB-200-2011.html. 

**Na koji način planirate validaciju rešenja?**
Validacija rešenja će se vršiti  koristeći deo inicijalnog data set-a odabirom odredjenog broja slika i proverom da li su dodeljeni odgovarajućoj grupi.

Asistent Stefan Anđelić.

**Comment by StefanAndjelic** [comment]
Pozdrav,

Ovo je čist problem klasifikacije, a ne klasterizacije. Postoje tačno određene (četiri) klase kojima ptica na slici može da pripada. K-means algoritam služi za klasterizaciju i za rezultat ima neoznačene grupe (klastere) jedinki, što se ne može primeniti na ovaj problem.

Sam problem je isuviše jednostavan za projekat, i morate ga promeniti ili makar nekako proširiti.

**Comment by jovica27** [comment]
Pozdrav,

Ja nisam dobro razumeo onda, do kada je rok za promenu?



2017-06-04 18:16 GMT+02:00 Stefan Andjelic <notifications@github.com>:

**Comment by StefanAndjelic** [comment]
Pokušaj do sutra u 13h

**Comment by jovica27** [comment]
Pozdrav,

Nisam stigao ranije  da odgovorim, radicu kolokvijum onda, jel treba sam da
se prijavljujem ili cete me vi prijaviti?

2017-06-04 22:11 GMT+02:00 Stefan Andjelic <notifications@github.com>:

**Comment by StefanAndjelic** [comment]
Nema problema, upisaću te u spisak za kolokvijum.
