### ISSUE TITLE
Klasterizacija saobraćajnih znakova 

### ISSUE THREAD

**Issue by filipetrovic** [ftn-ai-lab/ori-2017-e2#5]
**Ko su članovi tima, grupa sa vežbi? Ime, prezime, broj indeksa...**
 Filip Petrovic ra49-2014. Grupa sa vezbi: 5

**Problem koji se rešava (detaljniji opis)**
Klasterizovanje ili grupisanje saobracajnih znakova u 3 osnovne grupe: 

1. Saobracajni znakovi opasnosti
2. Saobracajni znakovi izricitih naredbi
3. Saobracajni znakovi obavestenja

**Algoritam/algoritmi koji će se koristiti**
K-Means alogoritam za klasterizaciju.

**Metrika za poređenje performansi algoritama i/ili parametara algoritma**
Koliko se slika od ukupnog broja slika pravilno rasporedilo po zadatim grupama. Resenje ce biti izrazeno u procentima.

**Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?**
Podaci koji ce se koristiti ce biti kompilacija manjih setova slika saobracajnih znakova. Skupljace se manuelno uz manje obrade svake slike.

**Na koji način planirate validaciju rešenja?**
Validacija resenja ce se izvrsiti odabirom fiksnog broja slika iz svake grupe znakova. Na kraju ce se procentualno izraziti tacnost klasterizacije nad odabranim slikama (koliko se od ukupnog broja odabranih slika dobro rasporedilo).

Asistent Dragan Vidakovic

**Comment by vdragan1993** [comment]
Problem je isuviše jednostavan za projekat, morate ga ili promeniti ili proširiti.
