### ISSUE TITLE
Klasterizacija životinja

### ISSUE THREAD

**Issue by ivan248** [ftn-ai-lab/ori-2017-e2#7]
**Ko su članovi tima, grupa sa vežbi? Ime, prezime, broj indeksa...**
 Ivan Jančić, RA157/2014 Grupa 5

**Problem koji se rešava (detaljniji opis):** 
Klasterovanje slika mačaka i pasa. Ideja je da se slike na osnovu svojih
karakteristika pridruže odgovarajućoj grupi/klasteru.

**Algoritam/algoritmi koji će se koristiti:**
Ponuđeno rešenje je implementirano uz pomoć K-MEANS algoritma.

**Metrika za poređenje performansi:**
 Procenat slika koje su tacno klasterizovane.

**Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?**
Podaci su sakupljeni manuelno, a predstavljaju 500 slika pasa i 500 slika macaka.

**Na koji način planirate validaciju rešenja?**
Validaciju rešenja ćemo vršiti nad 20% inicijalnog dataset-a(izdvojicu 100 slika pasa i 100 slika macaka i na kraju proveriti u kom se od klastera nalaze i izracunati tacnost u procentima).

Asistent Dragan Vidakovic

**Comment by ivan248** [comment]
POST /repos/:owner/:repo/issues/:number/vdragan1993

**Comment by vdragan1993** [comment]
Problem je isuviše jednostavan za projekat, morate ga ili promeniti ili proširiti.
